### ISSUE TITLE
status of the gpplayer and support for more

### ISSUE THREAD

**Issue by mckaygerhard** [gfxprim/gpplayer#1]
i check your gfxprim and it looks great.. search for all the subprojects.. 

what is the status of this gpplayer project?

i guess you can fork and change the behaviour of this example usage of gfxprim and provide a GUI interface command line..

i mean, this gpplayer is a implementation of a library (libasound and mpg123) using the gfxprim widgets..  

but what about a implementation of a command line interface using the gfxprim widgets? in that way more ugly maybe but more usefull for novice/lazy programmers

**Comment by metan-ucw** [comment]
Do I get it right that you want to run this application headless? Or do you want to be able to have some kind of interface how to control the application from a command line?

**Comment by mckaygerhard** [comment]
@metan-ucw  mostly control ffmpeg or mplayer.. so you only need to made a simple gui event implementing hole libraries api..  just like xt-player (gambas) does with mpv command line..

this means.. usage of mplayer or mpv with the --nogui flag command line, so you embebed into your interface.. is more cheap rather coding complex library api

**Comment by metan-ucw** [comment]
I know that mpv can be used by piping commands to the program. The reason why I used the mpg123 library for the gpplayer is that it's much more efficient than mpv. On modern desktop you probably will not see the difference, but on embedded hardware mpg123 is way better in terms of performance and CPU usage.

I do plan to add ogg and flac support later on, but I will do that by using the respective libraries or maybe libavcodec.h

**Comment by mckaygerhard** [comment]
> I know that mpv can be used by piping commands to the program. The reason why I used the mpg123 library for the gpplayer is that it's much more efficient than mpv. On modern desktop you probably will not see the difference, but on embedded hardware mpg123 is way better in terms of performance and CPU usage.

understood, of course.. but its limited to mp3, mp2 and mpeg layers.. also 

> 
> I do plan to add ogg and flac support later on, but I will do that by using the respective libraries or maybe libavcodec.h

you must use more your braind respect the situation: is that environment you pointed when these libs change api and abi, you have to change the code, **_in the case of mpeg123 its library was easy since its abi and api have not changed much in years ... something that allows maintenance to be really easy, however for libav it is different .. ffmpeg changes a lot in each version and you are one only person_**

Imagine .. you release version 3, and ffmpeg releases 3 more versions in same time.. and your project does not work with ffmpeg in recent distros .. and in my case is worse, I never use fashions or recent versions.. cos is stupid the usage of something that is not well knowed

**Comment by metan-ucw** [comment]
It took quite a time but gpplayer can use either mpg123 or llibmpv to embed mpv player to play music now.

**Comment by mckaygerhard** [comment]
WOW @metan-ucw this definitivelly need a check! give me some days and i m now interesting in make packages for alpinue linux and debian venenux :+1:

**Comment by metan-ucw** [comment]
There are some Debian packages in [OBS](https://build.opensuse.org/project/show/home:metan) however packaging gpplayer for Debian is still on my TODO.
